### ISSUE TITLE
Modifications suggested for INSTALL.sh and questions/erros

### ISSUE THREAD

**Issue by oliviermartinerie** [curtbraz/WhosHere#2]
Hello Curtis !

Thank you for sharing your very interesting tool. I would like to use it to know that kids are safe at home (or on time leaving home for school or activities) :)
And this is fun using raspberry pi for yet another interesting use case.

I had to do some tweaks before I could launch whoshere, so I felt it was good giving back to you.

First I started with a brand new image of Raspbian for RPI, which includes "Stretch" release of Raspbian : this was a nightmare as it comes with PHP7 and MariaDB instead of Mysql. The INSTALL.sh was lost.

Back to "Jessie" release of Raspbian, and still some problems. I had to install manually python and pip to at last be able to install python3-pymysql

Then I got to alter INSTALL.sh to correct (what I think are) typos:
```
pi@raspberrypi:~/devel/WhosHere $ diff INSTALL.sh INSTALL1.sh
91c91,92
< sed -i -e 's/PASSWORD_GOES_HERE/'$MySQLPassword'/g' dbconfig.py;
---
> ##sed -i -e 's/PASSWORD_GOES_HERE/'$MySQLPassword'/g' dbconfig.py;
> sed -i -e 's/PASSWORD_GOES_HERE/'$MySQLPassword'/g' dbconfig.php;
140c141
< mysql -u root -p $MySQLPassword WhosHere < MySQLSchema.sql;
---
> mysql -u root -p$MySQLPassword < MySQLSchema.sql;
```
> changing dbconfig.py to dbconfig.php
> modifying mysql command with removing space between "-p" and password, and removing name of database

In addition, my wifi card interface is "wlan0", and the script is supposed to swap "mon0" to the real name of interface in "run.py":
`sed -i -e 's/PHY_DEVICE_HERE/'$PhyDev'/g' run.py;`
but there is no PHY_DEVICE_HERE in run.py file so I manually changed all mon0 to wlan0, and errors were removed (hope it was the right thing to do).

The web page now seems OK, and the "options" leads to another page which seems OK too, but on the page there is this fatal sentence:

> The Collector Service is NOT Running!
> (run "sudo systemctl start whoshere.service" or "python run.py" if that fails)
> 

If I run `sudo systemctl start whoshere.service`, it does not throw any error on command line, but no improvement on the web page.

If I run `python run.py`, I get this message on command line and no better luck on the web page:
```
pi@raspberrypi:~/devel/WhosHere $ python run.py
command failed: No such file or directory (-2)
Capturing on 'wlan0'
tshark: Couldn't run /usr/bin/dumpcap in child process: Permission denied

```

I would be very grateful if you could help me with this, I pretty sure I am not too far from the perfect solution :)

Thank you very much,

Olivier

**Comment by curtbraz** [comment]
Hi Olivier!

I appreciate you reaching out, and am glad to hear you may be getting some
use out of it!  It's certainly been a fun project and a decent security
system.

First of all, thanks for the recommended updates.  I've been pushing
changes a lot lately adhoc and am not surprised the install script is no
longer working.  I'm running the most recent stable version of Raspbian
myself and it certainly does sound like you're close!

To me it looks like a permissions issue.  Can you run run.py as root with
sudo?  I apologize it's such a mess right now.  I need to put this in a
docker container or something so people don't have to go through this
hassle!

Please let me know if running run.py with sudo helps.  I have a feeling
there's more still wrong since the service isn't automatically running at
start so let me know if it doesn't work and I'll be happy to help you
troubleshoot to get it working!

Thanks,
Curtis


On Jan 13, 2018 6:25 PM, "oliviermartinerie" <notifications@github.com>
wrote:

Hello Curtis !

Thank you for sharing your very interesting tool. I would like to use it to
know that kids are safe at home (or on time leaving home for school or
activities) :)
And this is fun using raspberry pi for yet another interesting use case.

I had to do some tweaks before I could launch whoshere, so I felt it was
good giving back to you.

First I started with a brand new image of Raspbian for RPI, which includes
"Stretch" release of Raspbian : this was a nightmare as it comes with PHP7
and MariaDB instead of Mysql. The INSTALL.sh was lost.

Back to "Jessie" release of Raspbian, and still some problems. I had to
install manually python and pip to at last be able to install
python3-pymysql

Then I got to alter INSTALL.sh to correct (what I think are) typos:

pi@raspberrypi:~/devel/WhosHere $ diff INSTALL.sh INSTALL1.sh
91c91,92
< sed -i -e 's/PASSWORD_GOES_HERE/'$MySQLPassword'/g' dbconfig.py;
---
> ##sed -i -e 's/PASSWORD_GOES_HERE/'$MySQLPassword'/g' dbconfig.py;
> sed -i -e 's/PASSWORD_GOES_HERE/'$MySQLPassword'/g' dbconfig.php;
140c141
< mysql -u root -p $MySQLPassword WhosHere < MySQLSchema.sql;
---
> mysql -u root -p$MySQLPassword < MySQLSchema.sql;

changing dbconfig.py to dbconfig.php
modifying mysql command with removing space between "-p" and password, and
removing name of database

In addition, my wifi card interface is "wlan0", and the script is supposed
to swap "mon0" to the real name of interface in "run.py":
sed -i -e 's/PHY_DEVICE_HERE/'$PhyDev'/g' run.py;
but there is no PHY_DEVICE_HERE in run.py file so I manually changed all
mon0 to wlan0, and errors were removed (hope it was the right thing to do).

The web page now seems OK, and the "options" leads to another page which
seems OK too, but on the page there is this fatal sentence:

The Collector Service is NOT Running!
(run "sudo systemctl start whoshere.service" or "python run.py" if that
fails)

If I run sudo systemctl start whoshere.service, it does not throw any error
on command line, but no improvement on the web page.

If I run python run.py, I get this message on command line and no better
luck on the web page:

pi@raspberrypi:~/devel/WhosHere $ python run.py
command failed: No such file or directory (-2)
Capturing on 'wlan0'
tshark: Couldn't run /usr/bin/dumpcap in child process: Permission denied


I would be very grateful if you could help me with this, I pretty sure I am
not too far from the perfect solution :)

Thank you very much,

Olivier

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/curtbraz/WhosHere/issues/2>, or mute the thread

**Comment by oliviermartinerie** [comment]
Hello Curtis,

Thank you for this quick answer, I really appreciate.

Running 
`sudo python run.py
`throws another kind of errors:
```
pi@raspberrypi:~/devel/WhosHere $ sudo python run.py
command failed: No such file or directory (-2)
tshark: Lua: Error during loading:
 [string "/usr/share/wireshark/init.lua"]:46: dofile has been disabled due to running Wireshark as superuser. See http://wiki.wireshark.org/CaptureSetup/CapturePrivileges for help in running Wireshark as an unprivileged user.
Running as user "root" and group "root". This could be dangerous.
Capturing on 'wlan0'

```
and does not release command shell.
I hope it helps you in diagnosing what could be wrong, and what should I try ;)

Thank you again,

Olivier

**Comment by curtbraz** [comment]
Take a look at run.py and make sure the paths to the other scripts are
working.  I think it expects run.py and all other scripts to be in
/var/www/html/ which could be why you're receiving a "could not be found"
in your output.  If you don't mind, can you post the contents of run.py
here?

**Comment by oliviermartinerie** [comment]
I only see an executable referenced in the script: `/usr/bin/tshark`
which I can run from the shell without sudo (no error thrown even if there is no output).

I copied run.py in /var/www/html/WhosHere, but no better luck - I get the exact same errors / output.

Here is the content of run.py (which should be the same as in github, with "wlan0" replacing "mon0"):

```
#Server Connection to MySQL:

import pymysql.cursors
import re

conn = pymysql.connect(host= "localhost",
                  user="root",
                  passwd="password",
                  db="WhosHere")
x = conn.cursor()


## SETS UP YOUR WLAN FOR MONITOR MODE.  YOU MAY NEED TO CHANGE TO THE OUTPUT OF "iw list" FOR YOUR DEVICE THAT SUPPORTS MONITOR MODE!!

import subprocess
MonMode1 = subprocess.Popen(['sudo','iw','phy','phy1','interface','add','wlan0','type','monitor'],stdout=subprocess.PIPE)
MonMode2 = subprocess.Popen(['sudo','ifconfig','wlan0','up'],stdout=subprocess.PIPE)

## CALLS TSHARK AND FILTERS FOR PROBE REQUESTS
## /usr/bin/tshark -i mon0 -Y 'wlan.fc.type_subtype eq 4' -l
## /usr/bin/tshark -l -i mon0 -Y 'wlan.fc.type_subtype eq 4' -T fields -e wlan.sa -e radiotap.dbm_antsignal -e wlan_mgt.ssid
proc = subprocess.Popen(['/usr/bin/tshark','-l','-i','wlan0','-Y','wlan.fc.type_subtype eq 4','-T','fields','-e','wlan.sa_resolved','-e','radio
tap.dbm_antsignal','-e','wlan_mgt.ssid'],stdout=subprocess.PIPE)
#proc = subprocess.Popen(['/usr/bin/tshark','-i','mon0','-Y','wlan.fc.type_subtype eq 4','-l'],stdout=subprocess.PIPE)
#while True:
#  line = proc.stdout.readline()
for line in iter(proc.stdout.readline, ""):


#  if "Probe Request" in line:
  if "da:a1:19" not in line:
    ##linepostart=line.index(".") + 10
    #lineposend=line.index("\x09")
    #MAC=line[0:lineposend]

    line = line.rstrip("\n")
    values = line.split("\t")

    MAC=values[0]
    AP=values[2]
    DB=values[1]

    print values

    #print line
    #print MAC

## DUMPS MAC ADDRESSES FOR DEVICES INTO MySQL TABLE IN REAL-TIME VIA STDOUT

    try:
       x.execute("""CALL InsertMac(%s,%s,%s)""",(MAC,DB,AP))
       conn.commit()
    except:
       conn.rollback()

conn.close()

```

Thank you for your support !!!

Olivier

**Comment by oliviermartinerie** [comment]
Hello again,

I just figured out that the INSTALL script failed while updating the file whoshere.service (for unkwnown reason) at this step: `ExecStart=/usr/bin/python CHANGEME/run.py
`the CHANGEME where replaced by `pwd` (without being interpreted).

I updated the file and reexecuted this part of the install (including copying it at another location).

Now the webpage is not showing collector problem anymore, and display a very nice (

> The Collector Service is Running

) instead :)

Unfortunately, the table is now empty, after 15 minutes. Is there any log, or anything to debug, to know why it is not fed with all wifi terminals in house ?

Thank you again,

Olivier

**Comment by curtbraz** [comment]
Awesome, progress!  I was afraid that might be the case where variables
weren't getting updated for whatever reason.  Make sure all of your
WhosHere files are in /var/www/html/WhosHere.  As for debugging, kill the
service and run run.py again from the terminal.  I would first uncomment
the print command so you can see if you're picking up probe requests.  Make
sure your database configs are updated to use the correct credentials.  You
may validate by looking at the MySQL tables through the client to make sure
everything imported properly.  If not, you may have to import the sqldump
file manually.

On Jan 15, 2018 3:53 PM, "oliviermartinerie" <notifications@github.com>
wrote:

Hello again,

I just figured out that the INSTALL script failed while updating the file
whoshere.service (for unkwnown reason) at this step: ExecStart=/usr/bin/python
CHANGEME/run.pythe CHANGEME where replaced by pwd (without being
interpreted).

I updated the file and reexecuted this part of the install (including
copying it at another location).

Now the webpage is not showing collector problem anymore, and display a
very nice (

The Collector Service is Running

) instead :)

Unfortunately, the table is now empty, after 15 minutes. Is there any log,
or anything to debug, to know why it is not fed with all wifi terminals in
house ?

Thank you again,

Olivier

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/curtbraz/WhosHere/issues/2#issuecomment-357786846>, or mute
the thread

**Comment by oliviermartinerie** [comment]
Hello Curtis,

I verified I can correctly connect to the DB. All tables are empty except 'config'.
If I change a value in the "options" page, and then reload, I got the right value stored in Mysql.

I copied all files to `/var/www/html/WhosHere`

I did a `sudo chmod o+x /usr/bin/dumpcap` to cope with the 

> tshark: Couldn't run /usr/bin/dumpcap in child process: Permission denied

 error.

The `python run.py` sill throws one error:

> pi@raspberrypi:/var/www/html/WhosHere $ python run.py
> command failed: No such file or directory (-2)
> Capturing on 'wlan0

but I can't figure out which file/command it tries to execute with failure :(

And obviously still no data on the web page table.

Thank you, I feel I am not far for the succes ;)

Olivier

**Comment by curtbraz** [comment]
Hi Olivier,

Thanks for confirming the DB, seems the import was successful.  The only
file called in run.py is tshark.  Can you verify you have that installed
with `sudo apt-get install tshark` ?  Also, not sure if it's a typo or not,
but in your output where you said "Capturing on 'wlan0" you had an
unfinished single quote.

Thanks!

On Mon, Jan 15, 2018 at 6:13 PM, oliviermartinerie <notifications@github.com

**Comment by oliviermartinerie** [comment]
Hi Curtys !

Unfortunately, tshark is already installed :
```
pi@raspberrypi:~ $ sudo apt-get install tshark
Reading package lists... Done
Building dependency tree
Reading state information... Done
tshark is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 60 not upgraded.
```

And the missing quote was only a typo :

```
pi@raspberrypi:~ $ cd /var/www/html/WhosHere/
pi@raspberrypi:/var/www/html/WhosHere $ python run.py
command failed: No such file or directory (-2)
Capturing on 'wlan0'
```

What can we investigate ? What is your distribution, and which version (is it also Raspbian Jessie ?) ? What is your version of Python ? Is there any other tool that we need and is not in the INSTALL script but missing from my install ?

Thanks again for your time !

Olivier

**Comment by curtbraz** [comment]
I'm happy to do a screen share with you at some point!  I probably won't
get a chance until after today.  I'm running on stretch, and I'll have to
look when I'm home again to determine the python version.  Is it possible
your wlan device isn't in monitor mode, or doesn't support it?  Can you get
it to work using tools like airmon-ng?  I want to make sure there are
actually packets to throw into the database and you're not using the built
in wifi on the Raspberry Pi B for capture.

Thanks,

On Wed, Jan 17, 2018 at 2:20 AM, oliviermartinerie <notifications@github.com

**Comment by oliviermartinerie** [comment]
Hello Curtis,

I may be able to screenshare tomorrow but it may be complex to fin d a common time...

My Raspberry Pi does not support wifi (1st version, model B), so I hooked an Alfa AWUS036NEH which is supposed to manage quite well monitor mode.

I haven't the airmon package installed, so I will install it and test the monitor mode with it and let you know.

Thank you,

Olivier

**Comment by oliviermartinerie** [comment]
Hello Curtis !

Finally... here we are !

I switched to _wheezy_ in order to be closer of packages that INSTALL.sh tries to install by default.

I had difficult time to "install" pymysql. I finally ended up compiling python3.4 and got it right.
Then I had to adapt run.py to be "python3" compliant (the "str thing"...).

I also had to install (quite manually) aircrack to enable the card in monitor mode.

And... I was close to abandon when it finally worked out !!!!

So the table is now full of data, even if the web page still indicates that
> The Collector Service is NOT Running!
> (run "sudo systemctl start whoshere.service" or "python run.py" if that fails)

I also still get the error when running run.py
```
command failed: No such file or directory (-2)
```

So thank you very much for your great support, it is very kind of you.

I now have two hopefully final questions for you:
- what does "notify treshold" means ? is it a distance ? does the default "-100" mean that if the signal is stronger than "-100", it means the phone is at home ? (it is what I suppose).
- I got some IFTTT notifications, but there is only a unique text "The event named "WhosHere" occured on the Maker service", I suppose there should be a way to get the device name entered on the web page ?

Thank you again,

Olivier

**Comment by oliviermartinerie** [comment]
Hello Curtis, 

I auto-answer to me:

The "Collector Service is NOT Running" was due to the link to python, instead of python3.4 in whoshere.service. Now it's ok.

And the parameters in IFFFT are to be set to be used from IFFFT web settings page, that's now ok !

I can now close this case with great pleasure.

Thank you,

Olivier

**Comment by curtbraz** [comment]
Awesome!!  Glad to hear it's working!  Sorry it was such a pain to set up.
Enjoy!  Let me know if you have any questions regarding usage!

On Jan 20, 2018 1:15 PM, "oliviermartinerie" <notifications@github.com>
wrote:

Hello Curtis,

I auto-answer to me:

The "Collector Service is NOT Running" was due to the link to python,
instead of python3.4 in whoshere.service. Now it's ok.

And the parameters in IFFFT are to be set to be used from IFFFT web
settings page, that's now ok !

I can now close this case with great pleasure.

Thank you,

Olivier

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/curtbraz/WhosHere/issues/2#issuecomment-359191080>, or mute
the thread
