### ISSUE TITLE
pymysql.cursors

### ISSUE THREAD

**Issue by IanB999** [curtbraz/WhosHere#7]
using: 

Raspberry PI 3 b+
Linux raspberrypi 4.9.80-v7+ #1098 SMP Fri Mar 9 19:11:42 GMT 2018 armv7l GNU/Li

Issue:
python run.py    ,  indicates pymysql.cursors is not installed 

Fix:
# sudo pip install PyMySQL

PS: Any update on the randomisation ?

PS: I'm looking to  share "alert" MAC's between various   RaspPi boxes running this  code  , using a shared Google Sheets as the store for the new MAC . The new MAC will then get picked up from google  and loaded into each database , using python. Kindly let me know if you have been doing anything like this.

**Comment by curtbraz** [comment]
Thanks, I think I did this manually myself but forgot to update the install script.  

I've been putting most of my efforts into PhishAPI lately, but since this has been getting some recent attention I'd like to go back and make some significant updates.  I plan to make this portable as well, with a feature to "track down" AP's and BSSID's.  I've had a couple of cases now where this was used to help catch a theif, which I find interesting.

To answer your questions, no.. I haven't made any new progress on MAC randomisation, but plan to do that within the next updates.  I haven't used more than 1 box at a time, but leverage a high gain antenna that captures almost a half mile away.  I figure if I ever use two boxes I would just host a MySQL DB in the cloud and send all of the alert data there, instead of hosting it locally.  Then, have the web front end (also cloud) pointed to it.  We'd probably want to add "location" as a field if that were the case though, so you'd know which box is seeing which traffic.

**Comment by IanB999** [comment]
Many thanks I look forward to updates.

I have started to use Google sheets as a method to share macs between
installs, but as a stop gap and up and running solution I added some php to
allow manual additions of MAC to alert on. This would save on cloud costs ,
although I'd  agree it's probably no more than £100 a year for an EC2
instance to run this.

I wonder if having multiple raspberry devices locally you could use the dbi
signal as a method of triangulation to pin point a MAC to a street?

Would be good if you could add some notes around the logic used in
alerting. Initially when I set my Mrs MAC to alert as a test , I had to
wait for her to go out and come back to get an alert , I couldn't work out
what was not working and only when her Mac went out of range I realized all
was ok.

I'm a Solaris admin and oracle DBA by trade , but my php is not much good.

I wouldn't mind knowing the details of your antenna , I bought one but
power mine from a usb powered hub.

Regards

ian

**Comment by curtbraz** [comment]
Google Sheets is a great idea!  I already have a free community service on
phishapi.com on an EC2 instance, so I considered allowing people that use
this tool to point their data their if they felt comfortable doing so.  I
also thought it'd be cool to have a community of users eventually that
could report "suspicious devices" so that others would proactively be
alerted if that device came within range of them.  I plan on adding that to
my next round as well, but have to figure out what the infrastructure would
look like.

I did also think about the triangulation, which is a future wish list item,
just not sure how likely it'll be that I'll have time to actually add that
feature.  Who knows!

I'm an ex-MSSQL DBA myself!  Not much of a dev, so I make the back end do
most of the work for me.  I want to spruce up the front end a bit though
with some CSS and make it easier on the eyes.

https://www.amazon.com/gp/product/B0035GWTKK/ref=oh_aui_search_detailpage?ie=UTF8&psc=1

^ This is the antenna I'm using, with a 15dBI antenna in place of the one
that came with it.  Seems to work really well.

Thanks,

**Comment by IanB999** [comment]
could have done with this up and running in loads of neighbouring roads
today , crime has gone mental past two weeks. the.

I'd be quite happy to load my data to a shared aws db .


Thanks for the Arial.

**Comment by IanB999** [comment]
I ordered the wifi adapter today cheers ,  getting it deliver to a hotel in
NYC where my best pal is going for xmas . Saves on postage.

If you have any thing written done about the logic of your alerts  would
you kindly share .

cheers
ian

**Comment by IanB999** [comment]
Hi;
did you make any progress on enhancements to your code?

regards

**Comment by curtbraz** [comment]
Ian,

Sorry, I have not.  I haven't found the time but I see the benefits of
doing so.  I'll try to set aside some time in the coming month to crank out
a new and improved version.

Thanks,

**Comment by curtbraz** [comment]
Closing this issue.  I added "pip install pymysql" as a requirement in the INSTALL.sh file.  I plan on making improvements soon to this old repo so it can have a centralized DB and support for locating and reporting on bad ESSIDs/BSSIDs.
