### ISSUE TITLE
Kali run.py error

### ISSUE THREAD

**Issue by LuckyFishGeek** [curtbraz/WhosHere#8]
help me please

![20181208_140503](https://user-images.githubusercontent.com/29472751/49682638-8311c200-faaf-11e8-91ac-79858ecbbb7a.png)

**Comment by IanB999** [comment]
Remove the -e wlan_mgt.ssid part from run.py and lower in the code set the
value that is loaded into the dB for this value to '' ( single quote).
Sorry not at computer at present to post exact lines. This is a work around.

**Comment by RD31419** [comment]
What is your tshark version:
sudo tshark -v
I think that is a version issue.
Randy

**Comment by RD31419** [comment]
I think you will have to do the workaround IanB999 is recommending unless you change versions.  You are likely using the newest version of tshark.  I got the same error when using tshark on the newest version of raspbian because it will install version 2.6.3.   When I went back to an older "jessie" release of raspbian, it installed tshark version 1.12.1 and it does not get the error.  When I looked it up in the documentation here:
https://www.wireshark.org/docs/dfref/w/wlan_mgt.html
It says it works in 1.2.0 to 2.2.17 of wireshark, so I don't know if that means it does not work in the same versions of tshark beyond 2.2.17 or not, but is definitely works in the older release.  
I just can't get the web page to display any data on mine.  IanB999 has been helping but so far I cant get it to work, but I am close because the database has entries in it.
Randy

**Comment by EastwindZL** [comment]
> 我认为除非你改变版本，否则你必须做IanB999建议的解决方法。您可能正在使用最新版本的tshark。我在最新版本的raspbian上使用tshark时遇到了同样的错误，因为它将安装2.6.3版本。当我回到旧的“jessie”版本的raspbian时，它安装了tshark版本1.12.1并且它没有得到错误。当我在这里的文档中查找它时：
> [https](https://www.wireshark.org/docs/dfref/w/wlan_mgt.html)：[//www.wireshark.org/docs/dfref/w/wlan_mgt.html](https://www.wireshark.org/docs/dfref/w/wlan_mgt.html)
> 它说它工作在1.2.0到2.2.17的wireshark，所以我不知道如果这意味着它不能在超过2.2.17的相同版本的tshark中工作，但绝对适用于旧版本。
> 我只是无法让网页显示我的任何数据。IanB999一直在帮助，但到目前为止，我无法让它工作，但我很接近，因为数据库中有条目。
> 兰迪

Thank you for your answer and help for me.

**Comment by LuckyFishGeek** [comment]
> I think you will have to do the workaround IanB999 is recommending unless you change versions. You are likely using the newest version of tshark. I got the same error when using tshark on the newest version of raspbian because it will install version 2.6.3. When I went back to an older "jessie" release of raspbian, it installed tshark version 1.12.1 and it does not get the error. When I looked it up in the documentation here:
> https://www.wireshark.org/docs/dfref/w/wlan_mgt.html
> It says it works in 1.2.0 to 2.2.17 of wireshark, so I don't know if that means it does not work in the same versions of tshark beyond 2.2.17 or not, but is definitely works in the older release.
> I just can't get the web page to display any data on mine. IanB999 has been helping but so far I cant get it to work, but I am close because the database has entries in it.
> Randy

Thank you for your answer and help for me.

**Comment by EastwindZL** [comment]
> What is your tshark version:
> sudo tshark -v
> I think that is a version issue.
> Randy

Thank you for your answer and help for me.

**Comment by LuckyFishGeek** [comment]
@IanB999 Thank you for your answer and help for me.

**Comment by curtbraz** [comment]
Thanks all, for helping each other!  I'll install a new version of everything and update the code to support the latest releases.  Sorry you had to depend on workarounds, but glad you got it working!

**Comment by LuckyFishGeek** [comment]
> Thanks all, for helping each other! I'll install a new version of everything and update the code to support the latest releases. Sorry you had to depend on workarounds, but glad you got it working!

We really like your work! I look forward to it getting better and better, I hope we can bring you more

**Comment by curtbraz** [comment]
Closing this now that we know the newer version of tshark renamed the field to wlan.ssid.
